app = "Anti-G-boot-node"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
BOOT_NODE_PORT = "80"
HEALTH_PORT = "8080"

[[services]]
http_checks = []
internal_port = 80
protocol = "tcp"
script_checks = []
[[services.ports]]
port = 80
